import { Inter } from 'next/font/google'
import './globals.css'
import NavBar from '@/components/NavBar'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout ({ children }) {
  return (
    <html lang='es' className='flex flex-col-reverse'>
      <body className={inter.className}>
<<<<<<< HEAD
=======
        <NavBar />
>>>>>>> 3320725774b19cf8eb6b5eca0ccc816fa6457acc
        {children}
      </body>
    </html>
  )
}
