export const metadata = {
  title: 'Guillermo Putero',
  description: 'Generated by Guillermo Putero'
}

export default function RootLayout ({ children }) {
  return (
    <html lang='en'>
      <body>{children}</body>
    </html>
  )
}
