import { Rubik } from 'next/font/google'

const rubik = Rubik({
  subsets: ['latin'],
  display: 'swap'
})

export const metadata = {
  title: 'Iniciar Sesión',
  description: 'Generated by create next app'
}

export default function RootLayout ({ children }) {
  return (
    <html className={rubik.className} lang='es'>
      <body>{children}</body>
    </html>
  )
}
